<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiSentinel.Infrastructure\ApiSentinel.Infrastructure.csproj" />
    <ProjectReference Include="..\ApiSentinel.Modules.Identity\ApiSentinel.Modules.Identity.csproj" />
    <ProjectReference Include="..\ApiSentinel.Modules.ApiCatalog\ApiSentinel.Modules.ApiCatalog.csproj" />
    <ProjectReference Include="..\ApiSentinel.Modules.Monitoring\ApiSentinel.Modules.Monitoring.csproj" />
    <ProjectReference Include="..\ApiSentinel.Modules.Incidents\ApiSentinel.Modules.Incidents.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
